### ISSUE TITLE
infer and data

### ISSUE THREAD

**Issue by rongtongxueya** [anhp95/forest_attr_segment#1]
Great work and thanks for sharing your code.

I am also currently using 3dunet to classify tree species. My question is how to visualize a single image

**Comment by anhp95** [comment]
Hi @rongtongxueya,

Thank you for your interest. However I am not sure that I fully understand your question.

If you simply want to visualize a single image, you can just use  a third-party software such as QGIS or ArcGIS for visualization.

Or if you want to use python, I would suggest load it to a xarray.Dataset and plot it by matplotlib wrapper function.

**Comment by rongtongxueya** [comment]
Thank you for your quick reply to my question. My problem is that the dimension of the model saved by training is BDCHW; But the data I downloaded is a series of time, so I want to use the saved training model to perform an inferential visualization of the entire image, similar to the maping kind (similar to Fig. 7 in your paper). However, such data is of B1CHW dimension, which does not meet the data dimension required by the model

 
![fig7](https://github.com/anhp95/forest_attr_segment/assets/97833507/a9327b30-5709-465b-8a9d-5305545e619f)

**Comment by anhp95** [comment]
> However, such data is of B1CHW dimension, which does not meet the data dimension required by the model.

Just to clarify the data structure: it's organized as num_of_timeseries x num_of_bands x H x W.

Consider a single image, which has the shape num_of_bands x H x W. For instance, if you have 12 time-series images, each being a 32x32 (HxW) square image with 4 bands (R, G, B, NIR), the shape of each image would be 4x32x32. 

To obtain the data with the shape of 12 x 4 x 32 x 32 (num_of_timeseries x num_of_bands x H x W), you simply stack all 12 images together.

**Comment by rongtongxueya** [comment]
yes,but when you maping with a saved model, for example, does Figure 7 show one of the 12 images? Do we superimpose an image in the time dimension and use it as infer data? This is what puzzled me all the time. If I superimpose all the 12 data to form BDCHW and input it into the saved model to infer, I seem to think that time series information is not used.angway,thank you

**Comment by anhp95** [comment]
> yes,but when you maping with a saved model, for example, does Figure 7 show one of the 12 images? Do we superimpose an image in the time dimension and use it as infer data? 

Yes, that is correct for my case.

>This is what puzzled me all the time. If I superimpose all the 12 data to form BDCHW and input it into the saved model to infer, I seem to think that time series information is not used.angway,thank you

I agree that its original intent did not encompass the extraction of features from time series data, and while this concept may appear somewhat antiquated nowadays, it remains a superior option compared to utilizing a lone 2D image within a CNN.

**Comment by rongtongxueya** [comment]
Thank you for answering my questions
